# Generated by Django 5.2.5 on 2025-08-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='job',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvoiceJob',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
