# Generated by Django 5.2.5 on 2025-08-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0004_invoicestatus_delete_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicestatus',
            old_name='job',
            new_name='posting',
        ),
        migrations.RemoveField(
            model_name='invoicestatus',
            name='user',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
