# Generated by Django 5.2.5 on 2025-08-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0005_rename_job_invoicestatus_posting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceStatus',
            new_name='Invoice',
        ),
    ]
