# Generated by Django 5.2.5 on 2026-04-02 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0010_remove_jobposting_category_jobposting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
