# Generated by Django 5.2.5 on 2026-04-09 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0014_interviewsession_interviewparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='host',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_hosts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='title',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
