# Generated by Django 5.2.5 on 2026-04-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0015_remove_interviewsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'SẮP DIỄN RA'), ('STARTING', 'ĐANG DIỄN RA'), ('DONE', 'ĐÃ DIỄN RA')], default='PENDING', max_length=10),
        ),
    ]
