# Generated by Django 5.2.5 on 2026-04-20 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0016_interviewsession_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewparticipant',
            unique_together={('session', 'user')},
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='room_id',
        ),
        migrations.AddField(
            model_name='interviewparticipant',
            name='role',
            field=models.CharField(default='CANDIDATE', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='room_name',
            field=models.CharField(default='abc', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Sắp diễn ra'), ('ONGOING', 'Đang diễn ra'), ('DONE', 'Đã kết thúc'), ('CANCELLED', 'Đã huỷ')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewParticipantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobapis.interviewparticipant')),
            ],
        ),
        migrations.RemoveField(
            model_name='interviewparticipant',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='interviewparticipant',
            name='left_at',
        ),
    ]
