# Generated by Django 5.2.5 on 2026-04-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0017_alter_interviewparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='conversation',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_posting',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='jobapis.jobposting'),
            preserve_default=False,
        ),
    ]
