# Generated by Django 5.2.5 on 2026-04-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapis', '0018_remove_interviewsession_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='job_posting',
        ),
    ]
